<?php
/*
 * FACEBOOK CONFIG
*/
/*
 * FACEBOOK CONFIG
*/
DEFINE('EVENT_START_TIME', '2013-07-01');

DEFINE('FB_APP_ID', '200675913429181');
DEFINE('FB_SECRET', 'da45faf6cdce67a6cd82056baa75f50b');
DEFINE('FB_REDIRECT_URL', PROTOCOL."://".URL.'/?a=facebook_connect');

DEFINE('FB_PAGE_COUNT', 1);
DEFINE('FB_PAGE_ID1', '69182975870');
DEFINE('FB_PAGE_NAME1', 'entermarketing1');
DEFINE('FB_PAGE_LABEL1', 'likeEntermarketingFbPage');

/*
 * TWITTER CONFIG
*/
DEFINE('TW_CONSUMER_KEY', 'ZLOVdabMVhTMPFCFkuocw');
DEFINE('TW_CONSUMER_SECRET', 'B1GURnsfiflg2gADV6D8rFF85CurqVhAEvsOCZSw');
DEFINE('TW_ACCESS_TOKEN','1548476659-6VpjftxkTFfxqM56hMriuypjDI4Oe6ozxlf5Mjo');
DEFINE('TW_ACCESS_TOKEN_SECRET','4BKWXGqrJQLq7NbOE21ajafeOmXtA7tYJpFjc33OGYU');
DEFINE('TW_REDIRECT_URL', PROTOCOL."://".URL.'/?a=twitter_connect');

DEFINE('TW_ACCOUNT_COUNT', 1);
DEFINE('TW_ACCOUNT_ID1', '101890983');
DEFINE('TW_ACCOUNT_NAME1', 'entermarketing');
DEFINE('TW_ACCOUNT_LABEL1', 'Entermarketing');

DEFINE('TW_HASHTAG_COUNT', 2);
DEFINE('TW_HASHTAG_ID1', '#entermarketing');
DEFINE('TW_HASHTAG_LABEL1', 'Entermarketing');
//http://t.co/9KLVlpdKhP
DEFINE('TW_HASHTAG_ID2', 'gameon.entermarketing.com');
DEFINE('TW_HASHTAG_LABEL2', 'EntermarketingLink');



/*
 * LINKEDIN CONFIG
*/
DEFINE('LI_APP_KEY', 'iudtlwxpumye');
DEFINE('LI_SECRET', 'e6AUK96QHSFi0VtT');
DEFINE('LI_REDIRECT_URL', PROTOCOL."://".URL.'/?a=linkedin_connect');

DEFINE('LI_SUBSCRIPTION_COUNT', 1);
DEFINE('LI_SUBSCRIPTION_ID1', '110094');
DEFINE('LI_SUBSCRIPTION_NAME1', 'Netech');
DEFINE('LI_SUBSCRIPTION_LABEL1', 'Entermarketing');


/*
 * INSTAGRAM CONFIG
*/
DEFINE('IS_CLIENT_ID', '043d3b2f34624c3193e6b22684111e03');
DEFINE('IS_CLIENT_SECRET', '196b6f194d09438aa179da14275995ba');
DEFINE('IS_REDIRECT_URL', PROTOCOL."://".URL.'/?a=instagram_connect');

DEFINE('IS_ACCOUNT_COUNT', 0);

DEFINE('IS_HASHTAG_COUNT', 1);
DEFINE('IS_HASHTAG_ID1', 'Emc');



DEFINE('DIR_VENDOR', DIR_INC.'/vendor');


/*
 * YOUTUBE CONFIG
*/
DEFINE('YT_CLIENT_ID', '155014077704.apps.googleusercontent.com');
DEFINE('YT_CLIENT_SECRET','4zIgvDqg-4Vq8wkeEA6mF9YW');
DEFINE('YT_REDIRECT_URL', PROTOCOL."://".URL.'/?a=linkedin_connect');
DEFINE('YT_SUBSCRIPTION_COUNT',0);

