<?php
/*
 * FACEBOOK CONFIG
*/
/*
 * FACEBOOK CONFIG
*/
DEFINE('EVENT_START_TIME', '2013-10-14');

DEFINE('FB_APP_ID', '	166049330260165');
DEFINE('FB_SECRET', 'ef0947e80744f465641f898f41580e04');
DEFINE('FB_REDIRECT_URL', PROTOCOL."://".URL.'/?a=facebook_connect');

DEFINE('FB_PAGE_COUNT', 1);
DEFINE('FB_PAGE_ID1', '141205826079600');
DEFINE('FB_PAGE_NAME1', 'NetechCorporation');
DEFINE('FB_PAGE_LABEL1', 'likeNetechFbPage');

/*
 * TWITTER CONFIG
*/
DEFINE('TW_CONSUMER_KEY', 'AYbb8yvTcNDYVyInfDPvg');
DEFINE('TW_CONSUMER_SECRET', 'Zoa3H4NLqtH51Af1i3GKXQY0hwIsIfdb27tspHl7iO0');
DEFINE('TW_ACCESS_TOKEN','1548476659-eSHhRjryB436aEK5MaFXJGzFXqzIQFpTSQNVDpY');
DEFINE('TW_ACCESS_TOKEN_SECRET','NtOIpwTJ8lSHxAJsVGbGNI5FUmwBW0pnlyQ9JqumVE');
DEFINE('TW_REDIRECT_URL', PROTOCOL."://".URL.'/?a=twitter_connect');

DEFINE('TW_ACCOUNT_COUNT', 1);
DEFINE('TW_ACCOUNT_ID1', '175416474');
DEFINE('TW_ACCOUNT_NAME1', 'netechcorp');
DEFINE('TW_ACCOUNT_LABEL1', 'Netech');

DEFINE('TW_HASHTAG_COUNT', 2);
DEFINE('TW_HASHTAG_ID1', '#netechcorp');
DEFINE('TW_HASHTAG_LABEL1', 'Netech');
//http://t.co/9KLVlpdKhP
DEFINE('TW_HASHTAG_ID2', 'netech.entermarketing.com');
DEFINE('TW_HASHTAG_LABEL2', 'NetechLink');



/*
 * LINKEDIN CONFIG
*/
DEFINE('LI_APP_KEY', '3yd0sea30mam');
DEFINE('LI_SECRET', 'l3TiAjhynemCQwTK');
DEFINE('LI_REDIRECT_URL', PROTOCOL."://".URL.'/?a=linkedin_connect');

DEFINE('LI_SUBSCRIPTION_COUNT', 1);
DEFINE('LI_SUBSCRIPTION_ID1', '75843');
DEFINE('LI_SUBSCRIPTION_NAME1', 'Netech');
DEFINE('LI_SUBSCRIPTION_LABEL1', 'Netech');


/*
 * INSTAGRAM CONFIG
*/
DEFINE('IS_CLIENT_ID', '043d3b2f34624c3193e6b22684111e03');
DEFINE('IS_CLIENT_SECRET', '196b6f194d09438aa179da14275995ba');
DEFINE('IS_REDIRECT_URL', PROTOCOL."://".URL.'/?a=instagram_connect');

DEFINE('IS_ACCOUNT_COUNT', 0);

DEFINE('IS_HASHTAG_COUNT', 1);
DEFINE('IS_HASHTAG_ID1', 'Emc');



DEFINE('DIR_VENDOR', DIR_INC.'/vendor');


/*
 * YOUTUBE CONFIG
*/
DEFINE('YT_CLIENT_ID', '845940195026-isgh9hqi819mmru555iohhvn7je4ka0q.apps.googleusercontent.com');
DEFINE('YT_CLIENT_SECRET','uKfXnkh6chWIvljzsa4DuP0-');
DEFINE('YT_REDIRECT_URL', PROTOCOL."://".URL.'/?a=youtube_connect');
DEFINE('YT_SUBSCRIPTION_COUNT',1);
DEFINE('YT_SUBSCRIPTION_ID1', '75843');
DEFINE('YT_SUBSCRIPTION_NAME1', 'NetechCorporation');
DEFINE('YT_SUBSCRIPTION_LABEL1', 'Netech');

